/* 
=============================================================================== 
Query S3 - Gross Revenue Churn and Net Revenue Retention by Cohort 
=============================================================================== 
 
Business Question 
----------------- 
Of the MRR we had from a given monthly cohort 12 months ago, how much did we 
keep excluding expansion, and how much did we keep after accounting for 
expansion and contraction? 
 
Definitions 
----------- 
Cohort:
The first month in which an account has positive reconstructed MRR. 
 
Cohort Starting MRR:
The reconstructed MRR contributed by an account during its cohort month. 
 
Retained MRR:
The starting MRR associated with accounts that are still paying 12 months 
after their cohort month. 
 
Expansion MRR:
Additional MRR generated by retained accounts above their cohort starting MRR. 
 
Contraction MRR:
MRR lost by accounts that are still paying but have lower MRR after 
12 months. 
 
Churn MRR:
Starting MRR associated with accounts that are no longer paying 12 months 
after their cohort month. 
 
Gross Revenue Retention (GRR):
Retained MRR / Cohort Starting MRR 
 
Net Revenue Retention (NRR):
(Retained MRR + Expansion MRR - Contraction MRR) / Cohort Starting MRR 
 
Grain 
----- 
One row per monthly revenue cohort. 
 
Output 
------ 
cohort_month, 
cohort_starting_mrr, 
retained_mrr_12m, 
expansion_mrr_12m, 
contraction_mrr_12m, 
churn_mrr_12m, 
grr, 
nrr 
 
Business Interpretation 
----------------------- 
The cohort analysis shows that revenue retention varies across cohorts, with 
some cohorts experiencing meaningful churn and contraction while others retain 
a large proportion of their starting MRR. 
 
At the same time, expansion revenue is a major driver of overall performance. 
Several cohorts achieve NRR above 100%, demonstrating that revenue expansion 
from retained customers can offset losses from churn and contraction. 
 
Overall, the results indicate that the business is operating in an 
expansion-led retention environment: while gross retention remains an important 
area to monitor, existing customers who remain active are frequently increasing 
their spending over time. 
 
PM Recommendation 
----------------- 
Current World:
Expansion-Led Growth. 
 
The strong NRR performance indicates that expansion from retained customers is 
doing significant work in driving revenue growth. The recommendation is to 
invest further in customer success and identify the behaviors, product usage 
patterns, and customer segments associated with the highest levels of account 
expansion. 
 
Recommended next actions: 
 
• Invest further in customer success and account expansion initiatives. 
• Identify the product behaviors associated with high-expansion accounts. 
• Analyze which plans, customer segments, or cohorts generate the strongest 
  NRR. 
• Investigate cohorts with weaker GRR to identify churn and contraction risks. 
• Build early-warning indicators for accounts showing declining MRR before 
  they fully churn. 
• Replicate successful expansion patterns across the broader customer base. 
 
Sanity Checks Performed 
----------------------- 
 
1. GRR Upper Bound 
 
   Verified that: 
 
   GRR <= 1.0 
 
   Gross Revenue Retention excludes expansion revenue and therefore cannot 
   exceed 100%. 
 
   Result: 
   ✓ Passed. 
 
2. NRR Expansion Validation 
 
   Verified that NRR can exceed 1.0 when expansion revenue from retained 
   accounts exceeds the impact of contraction and churn. 
 
   Result: 
   ✓ NRR above 1.0 observed across the cohort results. 
 
3. Retention and Churn Reconciliation 
 
   Verified that: 
 
   GRR + (Churn MRR / Cohort Starting MRR) ≈ 1.0 
 
   This validates that the starting revenue base is appropriately reconciled 
   between retained and churned revenue. 
 
   Result: 
   ✓ Passed. 
 
4. Manual Arithmetic Validation 
 
   Spot-checked the GRR and NRR calculations using cohort-level revenue 
   values. 
 
   GRR:
 
   Retained MRR / Cohort Starting MRR 
 
   NRR:
 
   (Retained MRR + Expansion MRR - Contraction MRR)
   / Cohort Starting MRR 
 
   Result: 
   ✓ Matches query output. 
 
Design Note 
----------- 
MRR is reconstructed from subscription_events rather than relying directly on 
subscriptions.mrr because the subscription snapshot does not consistently 
reflect all revenue-changing events, including add-on attachments and certain 
plan changes. 
 
Monthly MRR is reconstructed by first aggregating mrr_delta at the 
account-month level and then calculating a cumulative MRR balance for each 
account. 
 
A complete account-month grid is then generated, allowing the latest available 
cumulative MRR value to be carried forward through months with no subscription 
event. This produces a monthly MRR snapshot that can be used to compare each 
account's cohort-start MRR with its MRR 12 months later. 
 
Future-dated subscription events after the established data cutoff of 
2026-06-15 are excluded to prevent invalid events from affecting the 
reconstructed revenue history. 
 
=============================================================================== 
*/

with monthly_mrr_delta as
(
    select
        account_id
        ,date_trunc('month', event_time)::date as event_month
        ,sum(mrr_delta) as monthly_delta
    from saas.subscription_events
    where event_time <= timestamp '2026-06-15 23:59:59'
    group by
        account_id
        ,date_trunc('month', event_time)::date
)

,cumulative_mrr as
(
    select
        account_id
        ,event_month
        ,monthly_delta
        ,sum(monthly_delta) over (
            partition by account_id
            order by event_month
        ) as cumulative_mrr
    from monthly_mrr_delta
)

,month_spine as
(
    select
        generate_series(
            min(event_month)
            ,max(event_month)
            ,interval '1 month'
        )::date as month
    from cumulative_mrr
)

,account_months as
(
    select
        a.account_id
        ,ms.month
    from (
        select distinct
            account_id
        from cumulative_mrr
    ) a
    cross join month_spine ms
)

,monthly_mrr as
(
    select
        am.account_id
        ,am.month
        ,(
            select
                cm.cumulative_mrr
            from cumulative_mrr cm
            where cm.account_id = am.account_id
                and cm.event_month <= am.month
            order by
                cm.event_month desc
            limit 1
        ) as mrr
    from account_months am
)

,cohort_accounts as
(
    select
        account_id
        ,month as cohort_month
        ,mrr as cohort_starting_mrr
    from
    (
        select
            account_id
            ,month
            ,mrr
            ,row_number() over (
                partition by account_id
                order by month
            ) as rn
        from monthly_mrr
        where mrr > 0
            and month + interval '12 months' <= (
                select max(month)
                from monthly_mrr
            )
    ) x
    where rn = 1
)

,cohort_12m as
(
    select
        ca.account_id
        ,ca.cohort_month
        ,ca.cohort_starting_mrr
        ,mm.mrr as mrr_12m
    from cohort_accounts ca
    left join monthly_mrr mm
        on ca.account_id = mm.account_id
        and mm.month = ca.cohort_month + interval '12 months'
)

,mrr_movements as
(
    select
        account_id
        ,cohort_month
        ,cohort_starting_mrr
        ,coalesce(mrr_12m, 0) as mrr_12m

        ,case
            when coalesce(mrr_12m, 0) > 0
                then cohort_starting_mrr
            else 0
        end as retained_mrr_12m

        ,case
            when coalesce(mrr_12m, 0) > cohort_starting_mrr
                then coalesce(mrr_12m, 0) - cohort_starting_mrr
            else 0
        end as expansion_mrr_12m

        ,case
            when coalesce(mrr_12m, 0) > 0
                and mrr_12m < cohort_starting_mrr
                then cohort_starting_mrr - mrr_12m
            else 0
        end as contraction_mrr_12m

        ,case
            when coalesce(mrr_12m, 0) = 0
                then cohort_starting_mrr
            else 0
        end as churn_mrr_12m
    from cohort_12m
)

select
    cohort_month
    ,sum(cohort_starting_mrr) as cohort_starting_mrr
    ,sum(retained_mrr_12m) as retained_mrr_12m
    ,sum(expansion_mrr_12m) as expansion_mrr_12m
    ,sum(contraction_mrr_12m) as contraction_mrr_12m
    ,sum(churn_mrr_12m) as churn_mrr_12m
    ,sum(retained_mrr_12m)
        / nullif(sum(cohort_starting_mrr), 0) as grr
    ,sum(
        retained_mrr_12m
        + expansion_mrr_12m
        - contraction_mrr_12m
    )
        / nullif(sum(cohort_starting_mrr), 0) as nrr
from mrr_movements
group by
    cohort_month
order by
    cohort_month;